### ISSUE TITLE
Tikrinant spintos versiją metama error

### ISSUE THREAD

**Issue by LaurynasVenck** [atviriduomenys/spinta#986]
Suinstaliuota ant lokalaus environment (Ubuntu 24.04) PYENV ir atsisiusta su PIP šiandien (11-28 spinta).
Paleidus ENV ir bandant gauti spintos versiją metama klaida:

spinta@laurynas:~$ source venv/bin/activate
(venv) spinta@laurynas:~$ spinta --version
Traceback (most recent call last):
  File "/opt/spinta/venv/bin/spinta", line 5, in <module>
    from spinta.cli.main import app
  File "/opt/spinta/venv/lib/python3.13/site-packages/spinta/cli/main.py", line 14, in <module>
    from spinta.cli import auth
  File "/opt/spinta/venv/lib/python3.13/site-packages/spinta/cli/auth.py", line 16, in <module>
    from spinta.auth import KeyFileExists, get_clients_path, ensure_client_folders_exist
  File "/opt/spinta/venv/lib/python3.13/site-packages/spinta/auth.py", line 47, in <module>
    from spinta.utils.config import get_clients_path, get_keymap_path, get_id_path, get_helpers_path
  File "/opt/spinta/venv/lib/python3.13/site-packages/spinta/utils/config.py", line 5, in <module>
    from spinta.core.config import RawConfig, DEFAULT_CONFIG_PATH
  File "/opt/spinta/venv/lib/python3.13/site-packages/spinta/core/config.py", line 37, in <module>
    resource_filename('spinta', 'config.yml').
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/spinta/venv/lib/python3.13/site-packages/spinta/utils/path.py", line 32, in resource_filename
    with importlib.resources.files(package) / target as ref:
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: 'PosixPath' object does not support the context manager protocol

**Comment by karina-klinkeviciute** [comment]
Pabandžiau taip (Ubuntu 22.04):

```
python3 -m venv venv
source venv/bin/activate
pip install spinta
spinta --version
```
Klaidos negavau, gavau atsakymą:
`0.1.79`

Vėliau pabandysiu su Ubuntu 24, bet gal galėtum parašyti tikslias komandas, kurias leidai?

**Comment by LaurynasVenck** [comment]
curl https://pyenv.run/ | bash
   cd /opt/spinta/
   python3 --version
   which pyenv
  ./.pyenv/bin/pyenv install 3.13.0
  .pyenv/versions/3.13.0/bin/python -m venv venv
   venv/bin/pip install spinta
   source venv/bin/activate
   spinta --version

**Comment by karina-klinkeviciute** [comment]
ačiū :)

**Comment by karina-klinkeviciute** [comment]
ChatGPT atsakymas, gal padės išsiaiškinti, kas negerai:

The error `'PosixPath' object does not support the context manager protocol` likely arises due to changes or stricter enforcement of context manager support in Python 3.13 compared to Python 3.12.

In Python, using `PosixPath` objects (from the `pathlib` module) as context managers (e.g., `with path as p:`) directly is not supported. The context manager protocol requires `__enter__` and `__exit__` methods, which `PosixPath` does not implement.

### Why It Works in Python 3.12
In earlier Python versions, including 3.12, some operations might have been more lenient, allowing `PosixPath` objects to be implicitly used in contexts where they don't explicitly support the context manager protocol. This could occur in environments with additional code handling `Path` objects indirectly.

### Why It Fails in Python 3.13
Python 3.13 likely introduced stricter validation for context manager usage, explicitly requiring objects used in `with` statements to implement the context manager protocol. As a result, the error occurs when attempting to use `PosixPath` objects incorrectly.

### Solution
To resolve this, ensure you're using `PosixPath` objects properly. For example:

- **Opening files with `pathlib.Path`:** Use the `open` method explicitly.

    ```python
    from pathlib import Path

    path = Path("example.txt")
    with path.open("r") as file:  # Correct way to use Path in a context manager
        content = file.read()
    ```

- **Avoid using `with` directly on `Path` objects:**

    ```python
    from pathlib import Path

    path = Path("example.txt")
    # Incorrect usage
    # with path as file:  # This raises the error in Python 3.13
    ```

- **Temporary workaround (if needed):** If you need to mimic the context manager for a `Path` object, you can create a wrapper class that implements `__enter__` and `__exit__`.

    ```python
    class PathContextManager:
        def __init__(self, path):
            self.path = path.open()
        
        def __enter__(self):
            return self.path
        
        def __exit__(self, exc_type, exc_value, traceback):
            self.path.close()
    
    from pathlib import Path

    path = Path("example.txt")
    with PathContextManager(path) as file:
        content = file.read()
    ```

If you share the specific code snippet causing the issue, I can help adjust it further!

**Comment by karina-klinkeviciute** [comment]
Su Python3.13 ir aš gavau tokią pačią klaidą, Ubuntu 22.04

**Comment by LaurynasVenck** [comment]
Patestavau ir aš su Python 3.12.7 versija - veikia. Tai  kaip viršuje rašei incompatibility su python 13.13 problema. Klausimas tada ar planuojate artimiausiu metu updatinti spintos klientą jog su 13.13 veiktu?

**Comment by karina-klinkeviciute** [comment]
Dėl atnaujinimo, kad veiktų su 3.13, reikėtų klausti @sirex, bet tikriausiai reikės tai padaryti

**Comment by sirex** [comment]
3.13 versija pasirodė vos prieš mėnesį, bet reikia pataisyti, kad būtų suderinamumas su naujausia Python versija.

**Comment by karina-klinkeviciute** [comment]
Added related, wider issue: #1039

**Comment by karina-klinkeviciute** [comment]
pasitestuot ir sutvarkyt šią klaidą: AttributeError: module 'pkgutil' has no attribute 'ImpImporter'


pabandyti, ar veikia su visom palaikomom (3.9, 3.10, 3.11, 3.12, 3.13)

**Comment by 04d4** [comment]
Galutinis sprendimas per:
#1386
#1372
